In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
raw_data = pd.read_csv("FIFA19.csv")

In [3]:
raw_data.head()

,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,16,Luis García,37,https://cdn.sofifa.org/players/4/19/16.png,Spain,https://cdn.sofifa.org/flags/45.png,71,71,KAS Eupen,https://cdn.sofifa.org/teams/2/light/2013.png,...,79.0,70.0,43.0,40.0,9.0,12.0,13.0,11.0,11.0,€1.1M
1,41,Iniesta,34,https://cdn.sofifa.org/players/4/19/41.png,Spain,https://cdn.sofifa.org/flags/45.png,86,86,Vissel Kobe,https://cdn.sofifa.org/teams/2/light/101146.png,...,89.0,67.0,57.0,56.0,6.0,13.0,6.0,13.0,7.0,€26.9M
2,80,E. Belözoğlu,37,https://cdn.sofifa.org/players/4/19/80.png,Turkey,https://cdn.sofifa.org/flags/48.png,79,79,Medipol Başakşehir FK,https://cdn.sofifa.org/teams/2/light/101014.png,...,80.0,65.0,67.0,60.0,7.0,11.0,7.0,14.0,8.0,€7.6M
3,164,G. Pinzi,37,https://cdn.sofifa.org/players/4/19/164.png,Italy,https://cdn.sofifa.org/flags/27.png,70,70,Padova,https://cdn.sofifa.org/teams/2/light/110912.png,...,68.0,74.0,71.0,66.0,5.0,15.0,7.0,6.0,13.0,€372K
4,657,D. Vaughan,35,https://cdn.sofifa.org/players/4/19/657.png,Wales,https://cdn.sofifa.org/flags/50.png,66,66,Notts County,https://cdn.sofifa.org/teams/2/light/1937.png,...,82.0,59.0,66.0,62.0,6.0,9.0,10.0,9.0,7.0,€263K

# Clean up missing and unwanted values

## Clean unwanted columns

In [4]:
raw_data.columns

Index(['ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall',
       'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes', 'Release Clause'],
      dtype='object')

In [5]:
data=raw_data.copy()
data=data.drop(["Photo", "Flag", "Club", "Club Logo", "Jersey Number", "Real Face", "Joined", "Loaned From", "Contract Valid Until"], axis=1)
data

,ID,Name,Age,Nationality,Overall,Potential,Value,Wage,Special,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,16,Luis García,37,Spain,71,71,€750K,€6K,1906,Right,...,79.0,70.0,43.0,40.0,9.0,12.0,13.0,11.0,11.0,€1.1M
1,41,Iniesta,34,Spain,86,86,€21.5M,€21K,2058,Right,...,89.0,67.0,57.0,56.0,6.0,13.0,6.0,13.0,7.0,€26.9M
2,80,E. Belözoğlu,37,Turkey,79,79,€4M,€23K,2047,Left,...,80.0,65.0,67.0,60.0,7.0,11.0,7.0,14.0,8.0,€7.6M
3,164,G. Pinzi,37,Italy,70,70,€240K,€2K,1882,Right,...,68.0,74.0,71.0,66.0,5.0,15.0,7.0,6.0,13.0,€372K
4,657,D. Vaughan,35,Wales,66,66,€150K,€4K,1781,Left,...,82.0,59.0,66.0,62.0,6.0,9.0,10.0,9.0,7.0,€263K
5,768,Felipe,33,Brazil,75,75,€2.7M,€13K,1535,Left,...,68.0,77.0,80.0,76.0,11.0,6.0,8.0,9.0,5.0,€4.9M
6,1179,G. Buffon,40,Italy,88,88,€4M,€77K,1334,Right,...,70.0,13.0,11.0,11.0,88.0,87.0,74.0,90.0,83.0,€7.4M
7,2147,M. Stekelenburg,35,Netherlands,73,73,€950K,€30K,1125,Right,...,59.0,9.0,15.0,14.0,71.0,72.0,76.0,73.0,73.0,€1.8M
8,2335,A. Wilbraham,38,England,63,63,€130K,€1K,1501,Right,...,69.0,24.0,20.0,19.0,12.0,13.0,10.0,10.0,9.0,€228K
9,2702,K. Ellison,39,England,57,57,€30K,€1K,1662,Left,...,71.0,41.0,36.0,34.0,7.0,11.0,6.0,14.0,6.0,€53K
10,3281,Tarantini,34,Portugal,75,75,€3.2M,€10K,1955,Right,...,82.0,72.0,71.0,59.0,12.0,6.0,16.0,7.0,16.0,€6.8M
11,3484,J. O'Shea,37,Republic of Ireland,69,69,€140K,€10K,1497,Right,...,69.0,72.0,70.0,68.0,9.0,14.0,13.0,10.0,14.0,€266K
12,3665,B. Nivet,41,France,71,71,€ 0,€5K,1785,Right,...,82.0,58.0,56.0,43.0,11.0,7.0,8.0,14.0,7.0,NaN
13,5479,Casillas,37,Spain,82,82,€1.5M,€10K,1308,Left,...,70.0,24.0,11.0,13.0,87.0,74.0,58.0,82.0,84.0,€3M
14,6826,G. Barry,37,England,72,72,€425K,€16K,1878,Left,...,81.0,80.0,73.0,65.0,7.0,13.0,9.0,7.0,12.0,€808K
15,7647,D. Dainelli,39,Italy,73,73,€270K,€2K,1419,Right,...,75.0,73.0,76.0,70.0,6.0,12.0,14.0,13.0,10.0,€419K
16,8205,Braga,35,Portugal,70,70,€750K,€5K,1858,Right,...,80.0,55.0,56.0,38.0,15.0,15.0,13.0,8.0,6.0,€1.6M
17,9014,A. Robben,34,Netherlands,84,84,€15.5M,€110K,2044,Left,...,85.0,30.0,26.0,26.0,10.0,8.0,11.0,5.0,15.0,€25.6M
18,9833,D. Boer,37,Netherlands,69,69,€70K,€3K,1142,Right,...,55.0,12.0,13.0,12.0,64.0,72.0,52.0,77.0,64.0,€102K
19,10466,S. Ishizaki,36,Sweden,67,67,€240K,€2K,1813,Right,...,69.0,65.0,51.0,38.0,6.0,13.0,6.0,10.0,11.0,€300K
20,10884,M. Flynn,37,Wales,59,59,€50K,€1K,1586,Right,...,60.0,60.0,46.0,45.0,9.0,13.0,12.0,7.0,10.0,€88K
21,10899,C. Porter,34,England,62,62,€160K,€4K,1597,Right,...,61.0,40.0,31.0,31.0,14.0,9.0,7.0,15.0,12.0,€280K
22,11381,M. Gilks,36,Scotland,67,67,€100K,€2K,1080,Right,...,48.0,15.0,14.0,17.0,66.0,70.0,65.0,68.0,64.0,€175K
23,11430,J. McCombe,35,England,53,53,€10K,€2K,1000,Right,...,43.0,51.0,51.0,53.0,6.0,14.0,12.0,11.0,14.0,€18K
24,11800,C. Weale,36,England,57,57,€10K,€1K,1117,Left,...,40.0,20.0,17.0,18.0,57.0,56.0,57.0,56.0,56.0,€18K
25,11811,P. Green,35,Republic of Ireland,63,63,€150K,€3K,1791,Right,...,63.0,58.0,63.0,62.0,13.0,11.0,10.0,14.0,11.0,€263K
26,12940,E. Pogatetz,35,Austria,68,68,€210K,€3K,1369,Left,...,63.0,67.0,69.0,62.0,8.0,8.0,9.0,10.0,8.0,€305K
27,13883,D. Whitaker,37,England,61,61,€80K,€1K,1708,Right,...,72.0,59.0,51.0,50.0,13.0,11.0,16.0,16.0,9.0,€140K
28,14907,A. Bizzarri,40,Argentina,76,76,€525K,€2K,1198,Right,...,60.0,11.0,12.0,11.0,76.0,74.0,66.0,82.0,76.0,€840K
29,16097,N. Rimando,39,United States,71,71,€160K,€3K,1247,Right,...,51.0,20.0,12.0,13.0,71.0,69.0,69.0,70.0,73.0,€240K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18177,246452,S. Bouzar,18,France,57,70,€160K,€1K,1428,Right,...,46.0,52.0,63.0,64.0,14.0,9.0,14.0,7.0,12.0,€333K
18178,246454,D. Revan,17,England,53,72,€110K,€1K,1233,Left,...,39.0,49.0,56.0,56.0,8.0,14.0,8.0,7.0,14.0,€278K
18179,246455,Pablo Ramón,17,Spain,60,81,€400K,€1K,1443,Right,...,55.0,57.0,62.0,61.0,11.0,14.0,10.0,14.0,5.0,€1M
18180,246456,D. Bajselmani,19,Netherlands,59,70,€220K,€1K,1506,Right,...,36.0,59.0,57.0,58.0,6.0,13.0,7.0,5.0,14.0,€363K
18181,246457,C. Ngonge,18,Belgium,63,84,€850K,€2K,1559,Left,...,60.0,11.0,35.0,35.0,15.0,7.0,10.0,7.0,8.0,€2.1M
18182,246462,D. García,21,Argentina,59,68,€240K,€2K,1411,Right,...,54.0,15.0,21.0,14.0,14.0,13.0,10.0,14.0,10.0,€408K
18183,246464,J. Theissen,20,Germany,57,68,€140K,€2K,868,Right,...,35.0,8.0,9.0,11.0,61.0,58.0,59.0,53.0,55.0,€280K
18184,246465,Guerrero,16,Spain,63,76,€625K,€1K,1645,Left,...,55.0,56.0,64.0,58.0,6.0,5.0,10.0,6.0,14.0,€1.4M
18185,246466,G. Pintidis,18,Germany,52,68,€100K,€2K,1398,Right,...,37.0,40.0,54.0,55.0,12.0,15.0,13.0,12.0,7.0,€223K
18186,246469,A. Urzi,18,Argentina,59,76,€325K,€1K,1436,Right,...,60.0,34.0,28.0,27.0,9.0,9.0,9.0,10.0,14.0,€691K
18187,246548,O. Sahraoui,17,Norway,52,67,€100K,€1K,1413,Right,...,43.0,40.0,44.0,46.0,14.0,14.0,9.0,14.0,8.0,€188K
18188,246549,M. Siby,21,France,54,61,€80K,€1K,1415,Right,...,44.0,48.0,52.0,59.0,7.0,10.0,6.0,7.0,7.0,€156K
18189,246550,G. Haag,18,France,55,72,€160K,€1K,1292,Right,...,45.0,51.0,62.0,59.0,11.0,9.0,12.0,13.0,9.0,€380K
18190,246552,O. Sverrisson,25,Sweden,54,57,€70K,€1K,1397,Left,...,39.0,53.0,56.0,57.0,8.0,14.0,14.0,13.0,15.0,€93K
18191,246565,B. Diakité,17,France,60,80,€375K,€2K,1514,Right,...,52.0,56.0,69.0,61.0,7.0,10.0,8.0,13.0,5.0,€1.1M
18192,246592,Algobia,19,Spain,60,77,€450K,€1K,1578,Right,...,60.0,49.0,58.0,54.0,9.0,15.0,7.0,12.0,10.0,€1.3M
18193,246593,Javito,17,Spain,56,72,€160K,€1K,1439,Right,...,50.0,60.0,51.0,51.0,12.0,14.0,11.0,7.0,8.0,€452K
18194,246594,H. Massengo,16,France,62,75,€450K,€2K,1651,Right,...,50.0,52.0,62.0,65.0,8.0,14.0,12.0,9.0,15.0,€1.1M
18195,246599,Guillem Jaime,19,Spain,64,80,€975K,€13K,1694,Right,...,66.0,52.0,55.0,56.0,9.0,11.0,12.0,10.0,6.0,€2.6M
18196,246600,K. Taylor,17,England,48,63,€60K,€1K,1355,Left,...,42.0,45.0,45.0,42.0,10.0,5.0,8.0,7.0,8.0,€143K
18197,246601,J. Rowland,16,England,51,66,€70K,€1K,1334,Right,...,52.0,36.0,31.0,30.0,12.0,10.0,7.0,6.0,12.0,€166K
18198,246602,A. Canessa,18,Italy,58,73,€260K,€1K,1335,Right,...,49.0,19.0,20.0,16.0,7.0,6.0,9.0,15.0,11.0,€566K
18199,246603,Matis Carvalho,19,Portugal,60,73,€300K,€1K,932,Right,...,51.0,10.0,13.0,12.0,59.0,59.0,59.0,59.0,61.0,€788K
18200,246606,Fran García,18,Spain,64,79,€825K,€9K,1644,Left,...,60.0,60.0,58.0,59.0,9.0,6.0,12.0,9.0,11.0,€2.2M
18201,246608,Fidalgo,21,Spain,65,75,€875K,€20K,1673,Right,...,68.0,46.0,51.0,47.0,10.0,9.0,10.0,11.0,9.0,€2M
18202,246609,J. Requena,19,Argentina,57,72,€220K,€1K,1555,Right,...,58.0,57.0,53.0,58.0,11.0,7.0,6.0,12.0,11.0,€468K
18203,246613,J. Zwarts,19,Netherlands,62,77,€650K,€1K,1502,Left,...,51.0,18.0,22.0,17.0,8.0,12.0,8.0,7.0,6.0,€1.3M
18204,246616,José Uche,18,Spain,58,69,€180K,€1K,1381,Left,...,43.0,59.0,57.0,48.0,13.0,12.0,9.0,14.0,7.0,€432K
18205,246617,Javi Mier,19,Spain,62,76,€650K,€1K,1581,Right,...,55.0,35.0,48.0,42.0,11.0,7.0,11.0,10.0,7.0,€1.4M
18206,246620,E. McCue,17,Sweden,51,74,€70K,€1K,1203,Right,...,49.0,49.0,49.0,46.0,9.0,13.0,11.0,15.0,10.0,€175K

In [6]:
data.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Value',
       'Wage', 'Special', 'Preferred Foot', 'International Reputation',
       'Weak Foot', 'Skill Moves', 'Work Rate', 'Body Type', 'Position',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes', 'Release Clause'],
      dtype='object')

## Clean unwanted rows based on individual columns

In [7]:
pd.set_option("display.max_columns", None)
data.describe(include="all")

,ID,Name,Age,Nationality,Overall,Potential,Value,Wage,Special,Preferred Foot,International Reputation,Weak Foot,Skill Moves,Work Rate,Body Type,Position,Height,Weight,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,Acceleration,SprintSpeed,Agility,Reactions,Balance,ShotPower,Jumping,Stamina,Strength,LongShots,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
count,18207.000000,18207,18207.000000,18207,18207.000000,18207.000000,18207,18207,18207.000000,18159,18159.000000,18159.000000,18159.000000,18159,18159,18147,18159,18159,16122,16122,16122,16122,16122,16122,16122,16122,16122,16122,16122,16122,16122,16122,16122,16122,16122,16122,16122,16122,16122,16122,16122,16122,16122,16122,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,16643
unique,NaN,17194,NaN,164,NaN,NaN,217,144,NaN,2,NaN,NaN,NaN,9,10,27,21,57,93,93,93,105,102,102,102,105,101,101,101,100,92,92,92,100,95,99,99,99,95,98,108,108,108,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1244
top,NaN,J. Rodríguez,NaN,England,NaN,NaN,€1.1M,€1K,NaN,Right,NaN,NaN,NaN,Medium/ Medium,Normal,ST,6'0,165lbs,61+2,61+2,61+2,63+2,61+2,61+2,61+2,63+2,61+2,61+2,61+2,61+2,58+2,58+2,58+2,61+2,61+2,62+2,62+2,62+2,61+2,61+2,63+2,63+2,63+2,61+2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,€1.1M
freq,NaN,11,NaN,1662,NaN,NaN,431,4900,NaN,13948,NaN,NaN,NaN,9810,10595,2152,2881,1483,705,705,705,745,713,713,713,745,744,744,744,804,762,762,762,804,713,660,660,660,713,669,634,634,634,669,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,557
mean,214298.338606,NaN,25.122206,NaN,66.238699,71.307299,NaN,NaN,1597.809908,NaN,1.113222,2.947299,2.361308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.734181,45.550911,52.298144,58.686712,42.909026,55.371001,47.170824,42.863153,52.711933,58.369459,64.614076,64.726967,63.503607,61.836610,63.966573,55.460047,65.089432,63.219946,65.311967,47.109973,55.868991,46.698276,49.958478,53.400903,48.548598,58.648274,47.281623,47.697836,45.661435,16.616223,16.391596,16.232061,16.388898,16.710887,NaN
std,29965.244204,NaN,4.669943,NaN,6.908930,6.136496,NaN,NaN,272.586016,NaN,0.394031,0.660456,0.756164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.364524,19.525820,17.379909,14.699495,17.694408,18.910371,18.395264,17.478763,15.327870,16.686595,14.927780,14.649953,14.766049,9.010464,14.136166,17.237958,11.820044,15.894741,12.557000,19.260524,17.367967,20.696909,19.529036,14.146881,15.704053,11.436133,19.904397,21.664004,21.289135,17.695349,16.906900,16.502864,17.034669,17.955119,NaN
min,16.000000,NaN,16.000000,NaN,46.000000,48.000000,NaN,NaN,731.000000,NaN,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,2.000000,4.000000,7.000000,4.000000,4.000000,6.000000,3.000000,9.000000,5.000000,12.000000,12.000000,14.000000,21.000000,16.000000,2.000000,15.000000,12.000000,17.000000,3.000000,11.000000,3.000000,2.000000,10.000000,5.000000,3.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN
25%,200315.500000,NaN,21.000000,NaN,62.000000,67.000000,NaN,NaN,1457.000000,NaN,1.000000,3.000000,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.000000,30.000000,44.000000,54.000000,30.000000,49.000000,34.000000,31.000000,43.000000,54.000000,57.000000,57.000000,55.000000,56.000000,56.000000,45.000000,58.000000,56.000000,58.000000,33.000000,44.000000,26.000000,38.000000,44.000000,39.000000,51.000000,30.000000,27.000000,24.000000,8.000000,8.000000,8.000000,8.000000,8.000000,NaN
50%,221759.000000,NaN,25.000000,NaN,66.000000,71.000000,NaN,NaN,1635.000000,NaN,1.000000,3.000000,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.000000,49.000000,56.000000,62.000000,44.000000,61.000000,48.000000,41.000000,56.000000,63.000000,67.000000,67.000000,66.000000,62.000000,66.000000,59.000000,66.000000,66.000000,67.000000,51.000000,59.000000,52.000000,55.000000,55.000000,49.000000,60.000000,53.000000,55.000000,52.000000,11.000000,11.000000,11.000000,11.000000,11.000000,NaN
75%,236529.500000,NaN,28.000000,NaN,71.000000,75.000000,NaN,NaN,1787.000000,NaN,1.000000,3.000000,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64.000000,62.000000,64.000000,68.000000,57.000000,68.000000,62.000000,57.000000,64.000000,69.000000,75.000000,75.000000,74.000000,68.000000,74.000000,68.000000,73.000000,74.000000,74.000000,62.000000,69.000000,64.000000,64.000000,64.000000,60.000000,67.000000,64.000000,66.000000,64.000000,14.000000,14.000000,14.000000,14.000000,14.000000,NaN
max,246620.000000,NaN,45.000000,NaN,94.000000,95.000000,NaN,NaN,2346.000000,NaN,5.000000,5.000000,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93.000000,95.000000,94.000000,93.000000,90.000000,97.000000,94.000000,94.000000,93.000000,96.000000,97.000000,96.000000,96.000000,96.000000,96.000000,95.000000,95.000000,96.000000,97.000000,94.000000,95.000000,92.000000,95.000000,94.000000,92.000000,96.000000,94.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000,NaN

### Checking "Age"

In [8]:
data["Age"].isnull().sum()

0

### Checking Nationality

In [9]:
data["Nationality"].isnull().sum()

0

### Checking Overall

In [10]:
data["Overall"].isnull().sum()

0

### Checking Potential

In [11]:
data["Potential"].isnull().sum()

0

### Checking Value

In [12]:
data["Value"].isnull().sum()

0

### Checking Wage

In [13]:
data["Wage"].isnull().sum()

0

### Checking Special

In [14]:
data["Special"].isnull().sum()

0

### Checking Preferred Foot

In [15]:
data["Preferred Foot"].isnull().sum()

48

Only 48 of such rows have a NaN value for "Preferred Foot", will drop these rows as they are insignificant

#### Creating Index to drop for Preferred Foot variable

In [16]:
index_to_drop_pf=[]

for i in range(len(data["Preferred Foot"])):
    if type(data["Preferred Foot"][i]) != str:
        index_to_drop_pf.append(i)
        
index_to_drop_pf

[245,
 337,
 580,
 1247,
 1688,
 2916,
 3925,
 3973,
 4706,
 5087,
 6439,
 6804,
 6932,
 7272,
 7521,
 7945,
 8610,
 9013,
 9014,
 9739,
 10136,
 10217,
 10502,
 11742,
 11885,
 12206,
 12755,
 13066,
 13946,
 14594,
 14796,
 15121,
 15229,
 15902,
 16035,
 16278,
 16823,
 16827,
 16830,
 17160,
 17163,
 17164,
 17165,
 17167,
 17788,
 18013,
 18018,
 18138]

### Checking International Reputation

In [17]:
data["International Reputation"].isnull().sum()

48

#### Creating Index to drop for International Reputation variable

In [18]:
type(data["International Reputation"][3])

numpy.float64

In [19]:
index_to_drop_ir_tuple=np.where(data["International Reputation"].isnull())

type(index_to_drop_ir_tuple)

tuple

In [20]:
index_to_drop_ir = []

for i in index_to_drop_ir_tuple:
    index_to_drop_ir.append(i)
    
index_to_drop_ir = np.asarray(index_to_drop_ir)

index_to_drop_ir = index_to_drop_ir.flatten()

index_to_drop_ir = index_to_drop_ir.tolist()

index_to_drop_ir

[245,
 337,
 580,
 1247,
 1688,
 2916,
 3925,
 3973,
 4706,
 5087,
 6439,
 6804,
 6932,
 7272,
 7521,
 7945,
 8610,
 9013,
 9014,
 9739,
 10136,
 10217,
 10502,
 11742,
 11885,
 12206,
 12755,
 13066,
 13946,
 14594,
 14796,
 15121,
 15229,
 15902,
 16035,
 16278,
 16823,
 16827,
 16830,
 17160,
 17163,
 17164,
 17165,
 17167,
 17788,
 18013,
 18018,
 18138]

Only 48 of such rows have a NaN value for "Preferred Foot", will drop these rows as they are insignificant

### Checking Weak Foot

In [21]:
data["Weak Foot"].isnull().sum()

48

#### Creating index to drop for Weak Foot variable

In [22]:
index_to_drop_wf_tuple=np.where(data["Weak Foot"].isnull())

index_to_drop_wf = []

for i in index_to_drop_wf_tuple:
    index_to_drop_wf.append(i)
    
index_to_drop_wf = np.asarray(index_to_drop_wf)

index_to_drop_wf = index_to_drop_wf.flatten()

index_to_drop_wf = index_to_drop_wf.tolist()

### Checking Skill Moves

In [23]:
data["Skill Moves"].isnull().sum()

48

#### Creating index to drop for Skill Moves variable

In [24]:
index_to_drop_sm_tuple=np.where(data["Skill Moves"].isnull())

index_to_drop_sm = []

for i in index_to_drop_sm_tuple:
    index_to_drop_sm.append(i)
    
index_to_drop_sm = np.asarray(index_to_drop_sm)

index_to_drop_sm = index_to_drop_sm.flatten()

index_to_drop_sm = index_to_drop_sm.tolist()

### Checking Work Rate

In [25]:
data["Work Rate"].isnull().sum()

48

In [26]:
index_to_drop_wr_tuple=np.where(data["Work Rate"].isnull())

index_to_drop_wr = []

for i in index_to_drop_wr_tuple:
    index_to_drop_wr.append(i)
    
index_to_drop_wr = np.asarray(index_to_drop_wr)

index_to_drop_wr = index_to_drop_wr.flatten()

index_to_drop_wr = index_to_drop_wr.tolist()

### Checking Body Type

In [27]:
data["Body Type"].isnull().sum()

48

In [28]:
index_to_drop_bt_tuple=np.where(data["Body Type"].isnull())

index_to_drop_bt = []

for i in index_to_drop_bt_tuple:
    index_to_drop_bt.append(i)
    
index_to_drop_bt = np.asarray(index_to_drop_bt)

index_to_drop_bt = index_to_drop_bt.flatten()

index_to_drop_bt = index_to_drop_bt.tolist()

Something seems wrong with Body Type, there are supposed to be 3 unique values from what I understand, but there seems to be more. Shall check on this

In [29]:
data["Body Type"].unique()

array(['Lean', 'Normal', 'Stocky', 'C. Ronaldo', nan, 'Akinfenwa',
       'Messi', 'Neymar', 'Courtois', 'Shaqiri', 'PLAYER_BODY_TYPE_25'],
      dtype=object)

Seems that "Akinfenwa", "C. Ronaldo", "Courtois", "Messi", "Neymar", "PLAYER_BODY_TYPE_25" & "Shaqiri" are unique values that are for specific rows only. The 3 main type of body is "Lean", "Normal" & "Stocky".

As such we will only adopt and encode the 3 main types and drop the rest.

In [30]:
akinfenwa = np.where(data["Body Type"]=="Akinfenwa")
ronaldo = np.where(data["Body Type"]=="C. Ronaldo")
messi = np.where(data["Body Type"]=="Messi")
neymar = np.where(data["Body Type"]=="Neymar")
courtois = np.where(data["Body Type"]=="Courtois")
shaqiri = np.where(data["Body Type"]=="Shaqiri")
p25 = np.where(data["Body Type"]=="PLAYER_BODY_TYPE_25")

In [31]:
index_to_drop_bt_weird = np.concatenate((akinfenwa, ronaldo, messi, neymar, courtois, shaqiri, p25))

index_to_drop_bt_weird

    
index_to_drop_bt_weird = np.asarray(index_to_drop_bt_weird)

index_to_drop_bt_weird = index_to_drop_bt_weird.flatten()

index_to_drop_bt_weird = index_to_drop_bt_weird.tolist()

index_to_drop_bt_weird

[637, 45, 699, 3255, 3412, 3668, 6411]

In [32]:
index_to_drop_bt_overall = list(set().union(index_to_drop_bt, index_to_drop_bt_weird))

index_to_drop_bt_overall.sort()

print(len(index_to_drop_bt_overall))

print(index_to_drop_bt_overall)

55
[45, 245, 337, 580, 637, 699, 1247, 1688, 2916, 3255, 3412, 3668, 3925, 3973, 4706, 5087, 6411, 6439, 6804, 6932, 7272, 7521, 7945, 8610, 9013, 9014, 9739, 10136, 10217, 10502, 11742, 11885, 12206, 12755, 13066, 13946, 14594, 14796, 15121, 15229, 15902, 16035, 16278, 16823, 16827, 16830, 17160, 17163, 17164, 17165, 17167, 17788, 18013, 18018, 18138]

### Checking Position

In [33]:
data["Position"].isnull().sum()

60

In [34]:
data["Position"].unique()

array(['RCM', 'LF', 'CM', 'LCM', 'CDM', 'LCB', 'GK', 'ST', 'LM', 'CB',
       'CAM', 'RM', 'RDM', 'RS', 'LB', 'LS', 'RCB', 'RW', 'LW', 'RB', nan,
       'RWB', 'LWB', 'LDM', 'CF', 'RF', 'LAM', 'RAM'], dtype=object)

In [35]:
index_to_drop_p_tuple=np.where(data["Position"].isnull())

index_to_drop_p = []

for i in index_to_drop_p_tuple:
    index_to_drop_p.append(i)
    
index_to_drop_p = np.asarray(index_to_drop_p)

index_to_drop_p = index_to_drop_p.flatten()

index_to_drop_p = index_to_drop_p.tolist()

### Checking Height

In [36]:
data["Height"].isnull().sum()

48

In [37]:
index_to_drop_h_tuple=np.where(data["Height"].isnull())

index_to_drop_h = []

for i in index_to_drop_h_tuple:
    index_to_drop_h.append(i)
    
index_to_drop_h = np.asarray(index_to_drop_h)

index_to_drop_h = index_to_drop_h.flatten()

index_to_drop_h = index_to_drop_h.tolist()

### Checking Weight

In [38]:
data["Weight"].isnull().sum()

48

In [39]:
index_to_drop_w_tuple=np.where(data["Weight"].isnull())

index_to_drop_w = []

for i in index_to_drop_w_tuple:
    index_to_drop_w.append(i)
    
index_to_drop_w = np.asarray(index_to_drop_w)

index_to_drop_w = index_to_drop_w.flatten()

index_to_drop_w = index_to_drop_w.tolist()

### Checking LS

In [40]:
data["LS"].isnull().sum()

2085

In [41]:
GK=data["Position"]=="GK"
GK.sum()

2025

In [42]:
2085-2025

60

##### _Seems like for the individual positional ratings like "LS", "ST", all the way to "RB", they will all have "GK" as missing values (all of them have the same number of values, 16122) and also (assumption) the 60 values which is missing in the data["Position"] variable. As such we will not be continuing the check on these positional rating variables. We will later on map all the outfield players to have 0 for "GK" positional rating and the opposite for all GK players._

### Checking Crossing

In [43]:
data["Crossing"].isnull().sum()

48

In [44]:
index_to_drop_cross_tuple=np.where(data["Crossing"].isnull())

index_to_drop_cross = []

for i in index_to_drop_cross_tuple:
    index_to_drop_cross.append(i)
    
index_to_drop_cross = np.asarray(index_to_drop_cross)

index_to_drop_cross = index_to_drop_cross.flatten()

index_to_drop_cross = index_to_drop_cross.tolist()

### Checking Finishing

In [45]:
data["Finishing"].isnull().sum()

48

In [46]:
index_to_drop_finish_tuple=np.where(data["Finishing"].isnull())

index_to_drop_finish = []

for i in index_to_drop_finish_tuple:
    index_to_drop_finish.append(i)
    
index_to_drop_finish = np.asarray(index_to_drop_finish)

index_to_drop_finish = index_to_drop_finish.flatten()

index_to_drop_finish = index_to_drop_finish.tolist()

### Checking HeadingAccuracy

In [47]:
data["HeadingAccuracy"].isnull().sum()

48

In [48]:
index_to_drop_head_tuple=np.where(data["HeadingAccuracy"].isnull())

index_to_drop_head = []

for i in index_to_drop_head_tuple:
    index_to_drop_head.append(i)
    
index_to_drop_head = np.asarray(index_to_drop_head)

index_to_drop_head = index_to_drop_head.flatten()

index_to_drop_head = index_to_drop_head.tolist()

### Checking ShortPassing

In [49]:
data["ShortPassing"].isnull().sum()

48

In [50]:
index_to_drop_shortp_tuple=np.where(data["ShortPassing"].isnull())

index_to_drop_shortp = []

for i in index_to_drop_shortp_tuple:
    index_to_drop_shortp.append(i)
    
index_to_drop_shortp = np.asarray(index_to_drop_shortp)

index_to_drop_shortp = index_to_drop_shortp.flatten()

index_to_drop_shortp = index_to_drop_shortp.tolist()

### Checking Volleys

In [51]:
data["Volleys"].isnull().sum()

48

In [52]:
index_to_drop_volley_tuple=np.where(data["Volleys"].isnull())

index_to_drop_volley = []

for i in index_to_drop_volley_tuple:
    index_to_drop_volley.append(i)
    
index_to_drop_volley = np.asarray(index_to_drop_volley)

index_to_drop_volley = index_to_drop_volley.flatten()

index_to_drop_volley = index_to_drop_volley.tolist()

### Checking Dribbling

In [53]:
data["Dribbling"].isnull().sum()

48

In [54]:
index_to_drop_drib_tuple=np.where(data["Dribbling"].isnull())

index_to_drop_drib = []

for i in index_to_drop_drib_tuple:
    index_to_drop_drib.append(i)
    
index_to_drop_drib = np.asarray(index_to_drop_drib)

index_to_drop_drib = index_to_drop_drib.flatten()

index_to_drop_drib = index_to_drop_drib.tolist()

### Checking Curve

In [55]:
data["Curve"].isnull().sum()

48

index_to_drop_curve_tuple=np.where(data["Curve"].isnull())

index_to_drop_curve = []

for i in index_to_drop_curve_tuple:
    index_to_drop_curve.append(i)
    
index_to_drop_curve = np.asarray(index_to_drop_curve)

index_to_drop_curve = index_to_drop_curve.flatten()

index_to_drop_curve = index_to_drop_curve.tolist()

### Checking FKAccuracy

In [56]:
data["FKAccuracy"].isnull().sum()

48

In [57]:
index_to_drop_FK_tuple=np.where(data["FKAccuracy"].isnull())

index_to_drop_FK = []

for i in index_to_drop_FK_tuple:
    index_to_drop_FK.append(i)
    
index_to_drop_FK = np.asarray(index_to_drop_FK)

index_to_drop_FK = index_to_drop_FK.flatten()

index_to_drop_FK = index_to_drop_FK.tolist()

### Checking LongPassing

In [58]:
data["LongPassing"].isnull().sum()

48

In [59]:
index_to_drop_LP_tuple=np.where(data["LongPassing"].isnull())

index_to_drop_LP = []

for i in index_to_drop_LP_tuple:
    index_to_drop_LP.append(i)
    
index_to_drop_LP = np.asarray(index_to_drop_LP)

index_to_drop_LP = index_to_drop_LP.flatten()

index_to_drop_LP = index_to_drop_LP.tolist()

### Checking BallControl

In [60]:
data["BallControl"].isnull().sum()

48

In [61]:
index_to_drop_BC_tuple=np.where(data["BallControl"].isnull())

index_to_drop_BC = []

for i in index_to_drop_BC_tuple:
    index_to_drop_BC.append(i)
    
index_to_drop_BC = np.asarray(index_to_drop_BC)

index_to_drop_BC = index_to_drop_BC.flatten()

index_to_drop_BC = index_to_drop_BC.tolist()

### Checking Acceleration

In [62]:
data["Acceleration"].isnull().sum()

48

In [63]:
index_to_drop_accel_tuple=np.where(data["Acceleration"].isnull())

index_to_drop_accel = []

for i in index_to_drop_accel_tuple:
    index_to_drop_accel.append(i)
    
index_to_drop_accel = np.asarray(index_to_drop_accel)

index_to_drop_accel = index_to_drop_accel.flatten()

index_to_drop_accel = index_to_drop_accel.tolist()

### Checking SprintSpeed

In [64]:
data["SprintSpeed"].isnull().sum()

48

In [65]:
index_to_drop_SS_tuple=np.where(data["SprintSpeed"].isnull())

index_to_drop_SS = []

for i in index_to_drop_SS_tuple:
    index_to_drop_SS.append(i)
    
index_to_drop_SS = np.asarray(index_to_drop_SS)

index_to_drop_SS = index_to_drop_SS.flatten()

index_to_drop_SS = index_to_drop_SS.tolist()

### Checking Agility

In [66]:
data["Agility"].isnull().sum()

48

In [67]:
index_to_drop_agi_tuple=np.where(data["Agility"].isnull())

index_to_drop_agi = []

for i in index_to_drop_agi_tuple:
    index_to_drop_agi.append(i)
    
index_to_drop_agi = np.asarray(index_to_drop_agi)

index_to_drop_agi = index_to_drop_agi.flatten()

index_to_drop_agi = index_to_drop_agi.tolist()

### Checking Reactions

In [68]:
data["Reactions"].isnull().sum()

48

In [69]:
index_to_drop_react_tuple=np.where(data["Reactions"].isnull())

index_to_drop_react = []

for i in index_to_drop_react_tuple:
    index_to_drop_react.append(i)
    
index_to_drop_react = np.asarray(index_to_drop_react)

index_to_drop_react = index_to_drop_react.flatten()

index_to_drop_react = index_to_drop_react.tolist()

### Checking Balance

In [70]:
data["Balance"].isnull().sum()

48

In [71]:
index_to_drop_bal_tuple=np.where(data["Balance"].isnull())

index_to_drop_bal = []

for i in index_to_drop_bal_tuple:
    index_to_drop_bal.append(i)
    
index_to_drop_bal = np.asarray(index_to_drop_bal)

index_to_drop_bal = index_to_drop_bal.flatten()

index_to_drop_bal = index_to_drop_bal.tolist()

### Checking ShotPower

In [72]:
data["ShotPower"].isnull().sum()

48

In [73]:
index_to_drop_shotp_tuple=np.where(data["ShotPower"].isnull())

index_to_drop_shotp = []

for i in index_to_drop_shotp_tuple:
    index_to_drop_shotp.append(i)
    
index_to_drop_shotp = np.asarray(index_to_drop_shotp)

index_to_drop_shotp = index_to_drop_shotp.flatten()

index_to_drop_shotp = index_to_drop_shotp.tolist()

### Checking Jumping

In [74]:
data["Jumping"].isnull().sum()

48

In [75]:
index_to_drop_jump_tuple=np.where(data["Jumping"].isnull())

index_to_drop_jump = []

for i in index_to_drop_jump_tuple:
    index_to_drop_jump.append(i)
    
index_to_drop_jump = np.asarray(index_to_drop_jump)

index_to_drop_jump = index_to_drop_jump.flatten()

index_to_drop_jump = index_to_drop_jump.tolist()

### Checking Stamina

In [76]:
data["Stamina"].isnull().sum()

48

In [77]:
index_to_drop_stam_tuple=np.where(data["Stamina"].isnull())

index_to_drop_stam = []

for i in index_to_drop_stam_tuple:
    index_to_drop_stam.append(i)
    
index_to_drop_stam = np.asarray(index_to_drop_stam)

index_to_drop_stam = index_to_drop_stam.flatten()

index_to_drop_stam = index_to_drop_stam.tolist()

### Checking Stength

In [78]:
data["Strength"].isnull().sum()

48

In [79]:
index_to_drop_str_tuple=np.where(data["Strength"].isnull())

index_to_drop_str = []

for i in index_to_drop_str_tuple:
    index_to_drop_str.append(i)
    
index_to_drop_str = np.asarray(index_to_drop_str)

index_to_drop_str = index_to_drop_str.flatten()

index_to_drop_str = index_to_drop_str.tolist()

### Checking LongShots

In [80]:
data["LongShots"].isnull().sum()

48

In [81]:
index_to_drop_lshot_tuple=np.where(data["LongShots"].isnull())

index_to_drop_lshot = []

for i in index_to_drop_lshot_tuple:
    index_to_drop_lshot.append(i)
    
index_to_drop_lshot = np.asarray(index_to_drop_lshot)

index_to_drop_lshot = index_to_drop_lshot.flatten()

index_to_drop_lshot = index_to_drop_lshot.tolist()

### Checking Aggression

In [82]:
data["Aggression"].isnull().sum()

48

In [83]:
index_to_drop_agg_tuple=np.where(data["Aggression"].isnull())

index_to_drop_agg = []

for i in index_to_drop_agg_tuple:
    index_to_drop_agg.append(i)
    
index_to_drop_agg = np.asarray(index_to_drop_agg)

index_to_drop_agg = index_to_drop_agg.flatten()

index_to_drop_agg = index_to_drop_agg.tolist()

### Checking Interceptions

In [84]:
data["Interceptions"].isnull().sum()

48

In [85]:
index_to_drop_inter_tuple=np.where(data["Interceptions"].isnull())

index_to_drop_inter = []

for i in index_to_drop_inter_tuple:
    index_to_drop_inter.append(i)
    
index_to_drop_inter = np.asarray(index_to_drop_inter)

index_to_drop_inter = index_to_drop_inter.flatten()

index_to_drop_inter = index_to_drop_inter.tolist()

### Checking Positioning

In [86]:
data["Positioning"].isnull().sum()

48

In [87]:
index_to_drop_pos_tuple=np.where(data["Positioning"].isnull())

index_to_drop_pos = []

for i in index_to_drop_pos_tuple:
    index_to_drop_pos.append(i)
    
index_to_drop_pos = np.asarray(index_to_drop_pos)

index_to_drop_pos = index_to_drop_pos.flatten()

index_to_drop_pos = index_to_drop_pos.tolist()

### Checking Vision

In [88]:
data["Vision"].isnull().sum()

48

In [89]:
index_to_drop_vis_tuple=np.where(data["Vision"].isnull())

index_to_drop_vis = []

for i in index_to_drop_vis_tuple:
    index_to_drop_vis.append(i)
    
index_to_drop_vis = np.asarray(index_to_drop_vis)

index_to_drop_vis = index_to_drop_vis.flatten()

index_to_drop_vis = index_to_drop_vis.tolist()

### Checking Penalties

In [90]:
data["Penalties"].isnull().sum()

48

In [91]:
index_to_drop_pen_tuple=np.where(data["Penalties"].isnull())

index_to_drop_pen = []

for i in index_to_drop_pen_tuple:
    index_to_drop_pen.append(i)
    
index_to_drop_pen = np.asarray(index_to_drop_pen)

index_to_drop_pen = index_to_drop_pen.flatten()

index_to_drop_pen = index_to_drop_pen.tolist()

### Checking Composure

In [92]:
data["Composure"].isnull().sum()

48

In [93]:
index_to_drop_comp_tuple=np.where(data["Composure"].isnull())

index_to_drop_comp = []

for i in index_to_drop_comp_tuple:
    index_to_drop_comp.append(i)
    
index_to_drop_comp = np.asarray(index_to_drop_comp)

index_to_drop_comp = index_to_drop_comp.flatten()

index_to_drop_comp = index_to_drop_comp.tolist()

### Checking Marking

In [94]:
data["Marking"].isnull().sum()

48

In [95]:
index_to_drop_mark_tuple=np.where(data["Marking"].isnull())

index_to_drop_mark = []

for i in index_to_drop_mark_tuple:
    index_to_drop_mark.append(i)
    
index_to_drop_mark = np.asarray(index_to_drop_mark)

index_to_drop_mark = index_to_drop_mark.flatten()

index_to_drop_mark = index_to_drop_mark.tolist()

### Checking StandingTackle

In [96]:
data["StandingTackle"].isnull().sum()

48

In [97]:
index_to_drop_standt_tuple=np.where(data["StandingTackle"].isnull())

index_to_drop_standt = []

for i in index_to_drop_standt_tuple:
    index_to_drop_standt.append(i)
    
index_to_drop_standt = np.asarray(index_to_drop_standt)

index_to_drop_standt = index_to_drop_standt.flatten()

index_to_drop_standt = index_to_drop_standt.tolist()

### Checking SlidingTackle

In [98]:
data["SlidingTackle"].isnull().sum()

48

In [99]:
index_to_drop_slidet_tuple=np.where(data["SlidingTackle"].isnull())

index_to_drop_slidet = []

for i in index_to_drop_slidet_tuple:
    index_to_drop_slidet.append(i)
    
index_to_drop_slidet = np.asarray(index_to_drop_slidet)

index_to_drop_slidet = index_to_drop_slidet.flatten()

index_to_drop_slidet = index_to_drop_slidet.tolist()

### Checking GKDiving

In [100]:
data["GKDiving"].isnull().sum()

48

In [101]:
index_to_drop_GKD_tuple=np.where(data["GKDiving"].isnull())

index_to_drop_GKD = []

for i in index_to_drop_GKD_tuple:
    index_to_drop_GKD.append(i)
    
index_to_drop_GKD = np.asarray(index_to_drop_GKD)

index_to_drop_GKD = index_to_drop_GKD.flatten()

index_to_drop_GKD = index_to_drop_GKD.tolist()

### Checking GKHandling

In [102]:
data["GKHandling"].isnull().sum()

48

In [103]:
index_to_drop_GKH_tuple=np.where(data["GKHandling"].isnull())

index_to_drop_GKH = []

for i in index_to_drop_GKH_tuple:
    index_to_drop_GKH.append(i)
    
index_to_drop_GKH = np.asarray(index_to_drop_GKH)

index_to_drop_GKH = index_to_drop_GKH.flatten()

index_to_drop_GKH = index_to_drop_GKH.tolist()

### Checking GKKicking

In [104]:
data["GKKicking"].isnull().sum()

48

In [105]:
index_to_drop_GKK_tuple=np.where(data["GKKicking"].isnull())

index_to_drop_GKK = []

for i in index_to_drop_GKK_tuple:
    index_to_drop_GKK.append(i)
    
index_to_drop_GKK = np.asarray(index_to_drop_GKK)

index_to_drop_GKK = index_to_drop_GKK.flatten()

index_to_drop_GKK = index_to_drop_GKK.tolist()

### Checking GKPositioning

In [106]:
data["GKPositioning"].isnull().sum()

48

In [107]:
index_to_drop_GKP_tuple=np.where(data["GKPositioning"].isnull())

index_to_drop_GKP = []

for i in index_to_drop_GKP_tuple:
    index_to_drop_GKP.append(i)
    
index_to_drop_GKP = np.asarray(index_to_drop_GKP)

index_to_drop_GKP = index_to_drop_GKP.flatten()

index_to_drop_GKP = index_to_drop_GKP.tolist()

### Checking GKReflexes

In [108]:
data["GKReflexes"].isnull().sum()

48

In [109]:
index_to_drop_GKR_tuple=np.where(data["GKReflexes"].isnull())

index_to_drop_GKR = []

for i in index_to_drop_GKR_tuple:
    index_to_drop_GKR.append(i)
    
index_to_drop_GKR = np.asarray(index_to_drop_GKR)

index_to_drop_GKR = index_to_drop_GKR.flatten()

index_to_drop_GKR = index_to_drop_GKR.tolist()

### Checking Release Clause

In [110]:
data["Release Clause"].isnull().sum()

1564

In [111]:
index_to_drop_RC_tuple=np.where(data["Release Clause"].isnull())

index_to_drop_RC = []

for i in index_to_drop_RC_tuple:
    index_to_drop_RC.append(i)
    
index_to_drop_RC = np.asarray(index_to_drop_RC)

index_to_drop_RC = index_to_drop_RC.flatten()

index_to_drop_RC = index_to_drop_RC.tolist()

index_to_drop_RC

[12,
 56,
 85,
 106,
 129,
 145,
 245,
 312,
 337,
 365,
 427,
 471,
 482,
 580,
 581,
 585,
 624,
 630,
 642,
 648,
 660,
 719,
 778,
 785,
 857,
 902,
 907,
 912,
 924,
 972,
 994,
 1006,
 1023,
 1030,
 1046,
 1091,
 1111,
 1124,
 1125,
 1155,
 1227,
 1234,
 1247,
 1249,
 1270,
 1299,
 1340,
 1381,
 1403,
 1435,
 1455,
 1460,
 1467,
 1506,
 1508,
 1513,
 1514,
 1517,
 1525,
 1589,
 1598,
 1675,
 1685,
 1688,
 1698,
 1699,
 1780,
 1808,
 1821,
 1838,
 1847,
 1872,
 1908,
 1912,
 1922,
 1935,
 1958,
 1979,
 1984,
 2004,
 2025,
 2045,
 2072,
 2076,
 2082,
 2091,
 2093,
 2110,
 2114,
 2131,
 2133,
 2135,
 2140,
 2166,
 2251,
 2252,
 2260,
 2271,
 2292,
 2333,
 2342,
 2348,
 2353,
 2365,
 2370,
 2397,
 2405,
 2410,
 2415,
 2416,
 2420,
 2449,
 2453,
 2460,
 2483,
 2494,
 2501,
 2504,
 2545,
 2551,
 2553,
 2554,
 2603,
 2622,
 2632,
 2640,
 2646,
 2647,
 2650,
 2668,
 2670,
 2673,
 2701,
 2724,
 2736,
 2834,
 2840,
 2841,
 2848,
 2850,
 2863,
 2888,
 2916,
 2918,
 2920,
 2928,
 2979,
 2988,
 2993,
 3019,
 3029,
 3066,
 3086,
 3091,
 3140,
 3145,
 3160,
 3164,
 3174,
 3187,
 3204,
 3265,
 3269,
 3279,
 3314,
 3329,
 3387,
 3392,
 3403,
 3408,
 3410,
 3445,
 3448,
 3454,
 3532,
 3537,
 3602,
 3604,
 3627,
 3645,
 3671,
 3673,
 3674,
 3681,
 3687,
 3714,
 3732,
 3740,
 3750,
 3756,
 3760,
 3765,
 3787,
 3791,
 3794,
 3799,
 3810,
 3827,
 3864,
 3869,
 3881,
 3888,
 3895,
 3902,
 3918,
 3925,
 3934,
 3938,
 3942,
 3951,
 3963,
 3971,
 3973,
 3996,
 4023,
 4027,
 4047,
 4075,
 4086,
 4101,
 4134,
 4155,
 4159,
 4181,
 4183,
 4217,
 4225,
 4227,
 4242,
 4267,
 4337,
 4357,
 4382,
 4388,
 4396,
 4397,
 4434,
 4446,
 4473,
 4482,
 4511,
 4550,
 4556,
 4570,
 4604,
 4618,
 4626,
 4640,
 4647,
 4664,
 4675,
 4706,
 4714,
 4715,
 4732,
 4734,
 4763,
 4780,
 4790,
 4813,
 4821,
 4822,
 4824,
 4825,
 4826,
 4827,
 4843,
 4845,
 4868,
 4926,
 4930,
 4935,
 4951,
 4954,
 4959,
 4998,
 5008,
 5021,
 5058,
 5059,
 5073,
 5075,
 5083,
 5087,
 5096,
 5157,
 5161,
 5183,
 5196,
 5203,
 5205,
 5208,
 5230,
 5256,
 5265,
 5269,
 5284,
 5299,
 5318,
 5323,
 5327,
 5351,
 5353,
 5355,
 5368,
 5384,
 5397,
 5408,
 5420,
 5430,
 5431,
 5438,
 5441,
 5456,
 5462,
 5465,
 5486,
 5493,
 5498,
 5501,
 5503,
 5509,
 5537,
 5562,
 5568,
 5579,
 5592,
 5594,
 5596,
 5615,
 5619,
 5633,
 5646,
 5661,
 5708,
 5710,
 5716,
 5723,
 5731,
 5739,
 5740,
 5756,
 5771,
 5779,
 5788,
 5795,
 5797,
 5821,
 5823,
 5824,
 5864,
 5873,
 5886,
 5888,
 5889,
 5890,
 5898,
 5907,
 5921,
 5922,
 5939,
 5954,
 5956,
 5957,
 5958,
 5959,
 5965,
 5983,
 5985,
 5989,
 5995,
 5996,
 5997,
 5999,
 6003,
 6021,
 6023,
 6044,
 6053,
 6066,
 6073,
 6075,
 6089,
 6130,
 6136,
 6141,
 6154,
 6177,
 6187,
 6194,
 6196,
 6203,
 6251,
 6254,
 6264,
 6268,
 6298,
 6299,
 6316,
 6337,
 6345,
 6376,
 6377,
 6378,
 6412,
 6417,
 6423,
 6439,
 6444,
 6453,
 6466,
 6468,
 6469,
 6480,
 6482,
 6489,
 6504,
 6518,
 6543,
 6548,
 6570,
 6576,
 6616,
 6630,
 6641,
 6654,
 6662,
 6680,
 6685,
 6690,
 6745,
 6747,
 6778,
 6804,
 6820,
 6846,
 6848,
 6856,
 6876,
 6889,
 6894,
 6895,
 6896,
 6906,
 6918,
 6923,
 6924,
 6925,
 6932,
 6933,
 6944,
 6945,
 6948,
 6955,
 6993,
 7063,
 7069,
 7075,
 7119,
 7121,
 7136,
 7138,
 7152,
 7159,
 7169,
 7181,
 7183,
 7196,
 7207,
 7208,
 7213,
 7215,
 7216,
 7239,
 7244,
 7250,
 7268,
 7272,
 7273,
 7287,
 7304,
 7312,
 7326,
 7335,
 7337,
 7338,
 7340,
 7381,
 7402,
 7403,
 7418,
 7432,
 7447,
 7457,
 7458,
 7459,
 7466,
 7479,
 7489,
 7515,
 7517,
 7521,
 7524,
 7528,
 7537,
 7551,
 7578,
 7613,
 7617,
 7649,
 7657,
 7660,
 7668,
 7685,
 7687,
 7693,
 7696,
 7698,
 7719,
 7727,
 7742,
 7747,
 7781,
 7782,
 7783,
 7794,
 7800,
 7805,
 7808,
 7812,
 7816,
 7834,
 7836,
 7844,
 7853,
 7861,
 7882,
 7883,
 7893,
 7905,
 7910,
 7912,
 7922,
 7941,
 7945,
 7946,
 7983,
 7987,
 8004,
 8014,
 8018,
 8020,
 8023,
 8024,
 8025,
 8038,
 8083,
 8086,
 8096,
 8101,
 8113,
 8124,
 8126,
 8129,
 8136,
 8138,
 8139,
 8162,
 8164,
 8172,
 8173,
 8175,
 8245,
 8259,
 8268,
 8270,
 8284,
 8288,
 8289,
 8295,
 8322,
 8323,
 8335,
 8336,
 8341,
 8344,
 8346,
 8349,
 8355,
 8358,
 8371,
 8389,
 8391,
 8415,
 8419,
 8421,
 8438,
 8455,
 8460,
 8469,
 8476,
 8477,
 8491,
 8495,
 8498,
 8503,
 8512,
 8515,
 8536,
 8544,
 8548,
 8549,
 8556,
 8558,
 8560,
 8561,
 8563,
 8572,
 8573,
 8579,
 8583,
 8586,
 8590,
 8591,
 8595,
 8599,
 8610,
 8612,
 8622,
 8626,
 8628,
 8641,
 8642,
 8646,
 8654,
 8665,
 8669,
 8672,
 8677,
 8683,
 8691,
 8697,
 8706,
 8722,
 8727,
 8734,
 8740,
 8744,
 8746,
 8754,
 8756,
 8775,
 8776,
 8784,
 8785,
 8789,
 8790,
 8792,
 8794,
 8795,
 8796,
 8821,
 8822,
 8838,
 8844,
 8851,
 8854,
 8859,
 8863,
 8868,
 8870,
 8877,
 8886,
 8901,
 8904,
 8907,
 8923,
 8924,
 8932,
 8946,
 8955,
 8957,
 8959,
 8961,
 8964,
 8972,
 8985,
 8988,
 8990,
 8994,
 9010,
 9013,
 9014,
 9017,
 9020,
 9029,
 9039,
 9044,
 9047,
 9069,
 9085,
 9086,
 9100,
 9112,
 9125,
 9126,
 9168,
 9172,
 9186,
 9188,
 9200,
 9204,
 9213,
 9230,
 9232,
 9259,
 9276,
 9277,
 9279,
 9293,
 9298,
 9306,
 9325,
 9343,
 9353,
 9356,
 9360,
 9362,
 9367,
 9368,
 9373,
 9376,
 9398,
 9406,
 9408,
 9411,
 9414,
 9419,
 9428,
 9441,
 9444,
 9445,
 9452,
 9453,
 9460,
 9463,
 9467,
 9476,
 9483,
 9485,
 9488,
 9493,
 9494,
 9495,
 9496,
 9501,
 9503,
 9517,
 9526,
 9532,
 9546,
 9551,
 9565,
 9566,
 9571,
 9599,
 9600,
 9604,
 9613,
 9637,
 9645,
 9647,
 9648,
 9649,
 9651,
 9656,
 9682,
 9704,
 9712,
 9713,
 9717,
 9730,
 9739,
 9742,
 9756,
 9757,
 9759,
 9762,
 9763,
 9764,
 9792,
 9799,
 9802,
 9813,
 9825,
 9826,
 9833,
 9843,
 9855,
 9856,
 9876,
 9877,
 9906,
 9910,
 9913,
 9914,
 9934,
 9978,
 9980,
 9995,
 9996,
 10000,
 10003,
 10009,
 10015,
 10017,
 10026,
 10029,
 10030,
 10037,
 10044,
 10046,
 10060,
 10061,
 10073,
 10075,
 10079,
 10084,
 10091,
 10110,
 10128,
 10132,
 10136,
 10157,
 10166,
 10179,
 10181,
 10186,
 10198,
 10201,
 10210,
 10217,
 10218,
 10220,
 10229,
 10237,
 10243,
 10282,
 10285,
 10301,
 10302,
 10303,
 10304,
 10305,
 10306,
 10307,
 10308,
 10313,
 10325,
 10341,
 10348,
 10353,
 10355,
 10357,
 10360,
 10363,
 10372,
 10382,
 10388,
 10389,
 10400,
 10403,
 10416,
 10426,
 10427,
 10433,
 10435,
 10449,
 10454,
 10456,
 10462,
 10468,
 10489,
 10492,
 10497,
 10499,
 10502,
 10514,
 10520,
 10521,
 10523,
 10524,
 10526,
 10532,
 10551,
 10554,
 10568,
 10576,
 10599,
 10601,
 10613,
 10642,
 10652,
 10668,
 10673,
 10678,
 10680,
 10696,
 10701,
 10707,
 10708,
 10715,
 10722,
 10726,
 10732,
 10738,
 10762,
 10778,
 10796,
 10801,
 10807,
 10816,
 10821,
 10823,
 10824,
 10826,
 10828,
 10829,
 10830,
 10834,
 10844,
 10852,
 10866,
 10870,
 10886,
 10892,
 10893,
 10894,
 10895,
 10912,
 10919,
 10926,
 10928,
 10942,
 10944,
 10949,
 10950,
 10953,
 10960,
 10966,
 10991,
 10996,
 11002,
 11005,
 11006,
 11007,
 11013,
 11014,
 11017,
 11027,
 11030,
 11049,
 11072,
 11074,
 11089,
 11158,
 11162,
 11180,
 11183,
 11192,
 11193,
 11195,
 11196,
 11202,
 11217,
 11223,
 11228,
 11231,
 11234,
 11244,
 11263,
 11267,
 11269,
 11274,
 11275,
 11282,
 11284,
 11289,
 11293,
 11308,
 11312,
 11319,
 11323,
 11330,
 11333,
 11334,
 11336,
 11338,
 11353,
 11359,
 ...]

## Comments

(1) Seems that most of the data have the same 48 missing variables, as such we will opt to drop these 48

(2) "Body Type" variable has some erroneous values in the form of names as body types, we will drop these values together with the 48 in (1)

(3) For positional ratings, we will not drop the "extra" missing values. Instead we will map it later on - outfield players will have 0 for "GK" & Goalkeepers will have 0 for outfield positional ratings

(4) As for "Release Clause", some players just do not have release clauses in their contracts (eg. most BPL players I know do not have it). As such we will not drop the players without release clauses. Instead we will assign the average value of the release clauses to the players who do not have it. We will then be able to see if having a higher than average release clause will affect the player potential.

## Combining the list of index to drop